import Head from "next/head";
import { useEffect, useState } from "react";
import {
  FormControl,
  FormLabel,
  FormHelperText,
  Input,
  Button,
  RadioGroup,
  Heading,
  Radio,
  Text,
  Textarea,
  Flex,
  Card,
  CardBody,
  HStack,
  Editable,
  EditableInput,
  EditableTextarea,
  EditablePreview,
  Image,
  Img,
} from "@chakra-ui/react";
import { FaTwitter, FaLinkedin, FaGithub } from "react-icons/fa";
import styles from "../styles/Home.module.css";


export default function Home() {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState([]);

  const [interests, setInterests] = 
  useState("");

  const inputInterest = (e) => {
    setInterests(e.target.value);
  };

  const [type, setType] =
  useState("");

  const inputType = (e) => {
    setType(e.target.value);
  };

  const handleSubmit = async (e) => {
    e.preventDefault()
    setLoading(true)
    const response = await fetch('/api/suggest',
    { method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        interests,
        type,
      }),    
    })

    const data = await response.json();
    setResult(data.data);
    setLoading(false);

  };

  useEffect(() => { if (result) { setLoading(false)} }, [result]);


  return (
    <div>
      <Head>
        <title>JOB GOBLIN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Flex direction="column" align="center" justify="center">
          <div w={100}>
         
            <Text
              className={styles.title}
              fontSize={{ base: "40px", md: "50px", lg: "56px" }}
            >
              Job Goblin
            </Text>
            <Text
              className={styles.description}
              fontSize={{ base: "20px", md: "24px", lg: "28px" }}
            >
              Optimising your job application pipeline
            </Text>
          </div>
          
          <div>
            <FormControl m={4}>
              <FormLabel> Paste the text from your CV here </FormLabel>
              <Textarea
                onChange={inputInterest}
                type="text"
                width="60vw"
                value={interests} />
            </FormControl>
            <FormControl m={4}>
              <FormLabel> Paste the text from the job vacancy you are applying to here </FormLabel>
              <Textarea
                onChange={inputType}
                type="text"
                width="60vw" />
            </FormControl>
            <Flex align="center" justify="center" m={4}>
              {loading && 
                (
                  <Button isLoading 
                    colorScheme="gray" size="md">
                    Write my cover letter
                  </Button>
              )}
              {!loading && (
                <Button onClick={handleSubmit} colorScheme="gray" size="md">
                    Write my cover letter
                </Button>
              )}
            </Flex>
          </div>
          <div>
          &nbsp;
          &nbsp;
          </div>
          
          <Editable value={result} width={800} size={'lg'}>
            <EditablePreview />
            <EditableTextarea padding={0} margin={0}/>
          </Editable>

        </Flex>

      </main><footer className={styles.footer}>
        <Flex direction="column" align="center" justify="center">
          <div>Liked the Project ? Connect with me and let me know !</div>
          <br />
          <HStack>
            <a
              href="https://twitter.com/foofoo4you/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Button colorScheme="twitter" leftIcon={<FaTwitter />} size="sm">
                Twitter
              </Button>
            </a>
            <a
              href="https://github.com/fuaadness"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Button
                style={{ background: "black", color: "white" }}
                leftIcon={<FaGithub />}
                size="sm"
              >
                GitHub
              </Button>
            </a>


          </HStack>
        </Flex>
      </footer>
    </div>
  );
}
